<a href="https://colab.research.google.com/github/harsita21/SID-2023/blob/main/Copy_of_Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>**SPECTRUM INTENSHIP DRIVE 2023.**</center>


## <center>**Welcome to the DS/ML internship of SID 2023.We are glad to have you with us.**</center>

### <center>**Ever wondered what exactly is Machine Learning?**</center>

<center>By definition, Machine learning provides computers with the ability to learn without being explicitly programmed.</center>

### <center>Bit complex to understand ? No worries,we have got your back.</center>

<center>Let’s try to understand Machine Learning in layman terms. Consider you are trying to toss a paper to a dustbin.After first attempt you realise that you have put too much force in it. After second attempt you realise you are closer to target but you need to increase your throw angle. What is happening here is basically after every throw we are learning something and improving the end result. We are programmed to learn from our experience.
We can do something similar with machines too. We can program a machine to learn from every attempts/experiences/data-points and then improve the outcome. </center>

### <center>**Still not clear? No worries. We assure that by the end of this journey you will be able to completely understand what this latest buzzword floating around means.**</center>

<center>

# INSTRUCTIONS

**How to use this notebook ?**

You can either download this notebook and use Jupyter Notebook on your local machine to view and use this notebook
or
use Google Colab on your browser to do the same.

- For viewing and editing this notebook with Jupyter Notebook on your local machine.
1. Go to **File > Download > Download .ipynb** (i.e the file extention for Jupyter Notebooks.)
1. Now open the downloaded .ipynb file using Jupyter Notebook and now you can edit this notebook .

- For viewing and editing this notebook with Google Colab
1. Go to **File > Save a copy in Drive**
1. If your brower pop-up was enabled the new file will open in a new tab else click on open in new tab in the dialog box.
1. Now you can edit the "Copy of {this file}" notebook that opened in the new tab and fill it up.

**Getting the required Files**

Some tasks require you to have some files and variable assignments for your code to execute before writing and executing your code so make sure to run the previous required cells.

- After running the first code cell below it will fetch the required data files necessay to complete this task and stores them in the same folder where the .ipynb file is stored. If you are using Jupyter Notebook on your local machine check the folder.

- If you are using Google Colab check for the folder symbol in the sidebar on leftmost of the screen and click it there you can see the required files. The files will be available till the session ends. In each new session you will need to run the cell to fetch the files.

# **TASK-1**





##### Run the below cell to download the csvs and files into your colab/jupyter notebook and start working with it. You will be needing all these for completing the task.

In [ ]:
!wget https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/creditcard.csv
!wget https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/bmi.csv
!wget https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/data.txt

--2023-10-09 17:48:42--  https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/creditcard.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13782835 (13M) [text/plain]
Saving to: ‘creditcard.csv.1’

creditcard.csv.1    100%[===================>]  13.14M  --.-KB/s    in 0.04s   

2023-10-09 17:48:42 (330 MB/s) - ‘creditcard.csv.1’ saved [13782835/13782835]

--2023-10-09 17:48:42--  https://raw.githubusercontent.com/Spectrum-CETB/Data-Science-AI/main/Datasets/bmi.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK


#### WE WILL BE COVERING 3 MOST IMPORTANT CONCEPTS OF ML IN THIS WEEK.
#### 1)PYTHON
#### 2)NUMPY
#### 3)PANDAS


**1**) Write python code to calculate Mean, Median, Mode, Variance and Standard Deviation of the numbers in the below list without using any libraries.

In [ ]:
# SID 2023
# Author: Harsita Mohanty

# Start of Program
import collections # for calculating mode
import math # for calculating standard deviation

#The following identifier will store the list of numbers
numbers = [488, 296, 374, 189, 326, 229,  14, 162, 917, 778, 908, 376, 567,
162, 923, 130, 263, 655, 577, 486, 961, 966, 792,  19, 941, 722,
286, 191, 138, 704, 481, 230, 437, 592, 244, 885,   7, 524, 514,
483,  89, 779, 279, 478, 185, 940, 385,  43, 163, 571, 867, 492,
269,  23, 796, 888, 898, 725, 337, 573, 375, 916,  90, 743, 117,
742, 944, 358, 547, 975, 499, 469, 721, 665, 639,  70, 612, 338,
733, 634, 358, 524, 598, 466, 696, 691, 511, 450, 699,  76, 216,
359, 859, 754, 210, 309, 745,  38, 934, 541]

#Calculation for mean
mean=sum(numbers)/len(numbers)

#Calculation for median
numbers.sort()
if len(numbers)%2==0:
   median=(numbers[len(numbers)//2 - 1]+numbers[len(numbers)//2])/2
else:
  median = numbers[len(numbers)//2]

#Calculation for mode
def mode(lst):
    # calculate the frequency of each item
    data = collections.Counter(lst)
    data_list = dict(data)

    # Find the highest frequency
    max_value = max(list(data.values()))
    mode_val = [num for num, freq in data_list.items() if freq == max_value]
    if len(mode_val) == len(lst):
        print("No mode in the list") # This will not be printed
    else:
        return ( ', '.join(map(str, mode_val)))

#Calculation for variance
mean_squared_difference = [(x - mean)**2 for x in numbers]
variance = sum(mean_squared_difference)/len(numbers)

#Calculation for standard deviation
std=math.sqrt(variance)


# Now we will print each of the calculations we did above
print(f"Mean: {mean}")
print(f"Median: {median}")
print("Mode: ", mode(numbers))
print(f"Variance: {variance}")
print(f"Standard deviation: {std}")

# End of Program


Mean: 499.38
Median: 495.5
Mode:  162, 358, 524
Variance: 78991.79559999998
Standard deviation: 281.05479109952915


2) Use the lambda and map() to square the numbers in the numbers list and store them in a newly created list known as squared. Then use filter() to create a  new list of all even numbers from the squared list.

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
#squaring the numbers using map() and lambda
sqrd=list(map(lambda x: x**2,numbers))
# filtering even numbers using map() and lambda
even_sqrd = list(filter(lambda x: x%2==0,sqrd))

#printing the results
print("Squared numbers:",sqrd)
print("Even squared numbers:",even_sqrd)
#end of program

Squared numbers: [49, 196, 361, 529, 1444, 1849, 4900, 5776, 7921, 8100, 13689, 16900, 19044, 26244, 26244, 26569, 34225, 35721, 36481, 44100, 46656, 52441, 52900, 59536, 69169, 72361, 77841, 81796, 87616, 95481, 106276, 113569, 114244, 128164, 128164, 128881, 139876, 140625, 141376, 148225, 190969, 202500, 217156, 219961, 228484, 231361, 233289, 236196, 238144, 242064, 249001, 261121, 264196, 274576, 274576, 292681, 299209, 321489, 326041, 328329, 332929, 350464, 357604, 374544, 401956, 408321, 429025, 442225, 477481, 484416, 488601, 495616, 519841, 521284, 525625, 537289, 550564, 552049, 555025, 568516, 605284, 606841, 627264, 633616, 737881, 751689, 783225, 788544, 806404, 824464, 839056, 840889, 851929, 872356, 883600, 885481, 891136, 923521, 933156, 950625]
Even squared numbers: [196, 1444, 4900, 5776, 8100, 16900, 19044, 26244, 26244, 44100, 46656, 52900, 59536, 81796, 87616, 106276, 114244, 128164, 128164, 139876, 141376, 202500, 217156, 228484, 236196, 238144, 242064, 264196, 2

3)Sort the below dictionary in descending order of the age of employees.

In [ ]:
'''
Key - Name
Value - [Vaccination Status,Age]
'''
data = {'Ben':['Vaccinated',35],'Luke':['Not Vaccinated',28],'Anakin':['Vaccinated',55],'Leia':['Vaccinated',28],'Han':['Not Vaccinated',60]}
# SID 2023
# Author: Harsita Mohanty
#start of program
#sorting the data given above to reach the solution
sorted_info=dict(sorted(data.items(),key=lambda item: item[1][1], reverse=True))
for name, details in sorted_info.items():
  print(f"{name}: {details[0]}, Age: {details[1]}")
#end of program

Han: Not Vaccinated, Age: 60
Anakin: Vaccinated, Age: 55
Ben: Vaccinated, Age: 35
Luke: Not Vaccinated, Age: 28
Leia: Vaccinated, Age: 28


4)Using file handling, extract and read data from the data.txt file and find the most common occuring 5 words.

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
# to view the content of the file
with open('data.txt', 'r') as file:
    text = file.read()

# Tokenize the text into words
words = text.split()

# Creating a dictionary  to store the word frequencies
word_count = {}

#Counting the frequencies of each word
for word in words:
  word = word.lower()
  word = word.strip(".,!?():\"'")

  if word in word_count:
     word_count[word] +=1
  else:
     word_count[word] = 1

# decreasing order of frequencies
sorted_words = sorted(word_count.items(), key=lambda x:x[1], reverse = True)

#To get the top 5 most common words
top_5_words= sorted_words [:5]

for word, frequency in top_5_words :
  print(f"{word}:{frequency}")
#end of program

learning:14
machine:10
of:8
to:6
is:5


### 2)Numpy

In [ ]:
# run this cell and then proceed further
import numpy as np

* You will be given few matrices and you have to write a few lines of code which will be resulting the following outputs.

In [ ]:
mat = np.arange(0,25).reshape(5,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

1)The given array is above i.e (mat).
- You have to write a code such that the output looks like-
      array([[ 5,  6,  7,  8,  9],
             [10, 11, 12, 13, 14],
             [15, 16, 17, 18, 19]])

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import numpy as np
mat = np.arange(0,25).reshape(5,5)
#using slicing operation in numpy
mat[1:4,0:5]
#end of program


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

2)Convert the array 'x' into a 3x4 matrix

In [ ]:
x= np.arange(0,12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import numpy as np
x = np.arange(0,12).reshape(3,4)
#using reshape in above matrix to convert
x
#end of program

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

3) Find the inverse and transpose of the 3x4 matrix obtained above.

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import numpy as np
x
transpose_mat=np.transpose(x)
print ("Original matrix x is")
[print(x)]
print("Tranpose of the matrix is")
print(transpose_mat)

#the matrix in the question is a 3x4 matrix, which means it is not a sqaure matrix. Since it is not a square matrix, inverse of the matrix is not possible.
#end of program

Original matrix x is
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Tranpose of the matrix is
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


4) Write a code to find the position of all zeros present in the matrix 'y

In [ ]:
y=np.array(([0,5,9,0],[0,0,4,7],[9,3,0,6]))
y

array([[0, 5, 9, 0],
       [0, 0, 4, 7],
       [9, 3, 0, 6]])

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import numpy as np
y = np.array(([0,5,9,0],[0,0,4,7],[9,3,0,6]))
#to find the position of zeroes
position_of_zeros=np.argwhere(y==0)
print("position of zeroes is")
for position in position_of_zeros:
    print(f"Row: {position[0]},Column: {position[1]}")
#end of program

position of zeroes is
Row: 0,Column: 0
Row: 0,Column: 3
Row: 1,Column: 0
Row: 1,Column: 1
Row: 2,Column: 2


### 3)Pandas

In [ ]:
# run this cell and then proceed further
import pandas as pd

#### Read the data from the csv named "bmi.csv" and complete the task that follows.
1)Your first task is to create a new column in the dataframe named "BMI" index, which reads data from the "Weight" and "Height" Column, and calculates the BMI based on this. Display the top 10 rows of this dataframe after adding the new column.


In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
animal_data=pd.read_csv('bmi.csv')
#above code to see the data once
df=pd.DataFrame(animal_data)
df['BMI']= df['weight(in kg)'] / (df['height(in m)'] **2)
#creating a new column for BMI
print(df.head(10))
#printing first 10 rows of the dataframe
#end of program


  animal  age  weight(in kg)  height(in m)        BMI
0    cat    3             14           1.3   8.284024
1    dog    9             11           1.2   7.638889
2    dog    1              5           1.2   3.472222
3    cat   10              9           0.9  11.111111
4    cat    8              5           1.2   3.472222
5    cat    2             11           1.1   9.090909
6    dog   10             14           1.0  14.000000
7    dog    8              9           1.0   9.000000
8    cat   10             12           0.8  18.750000
9    cat    6              9           0.7  18.367347


2)From the dataframe, find out the count, mean ,standard deviation ,datatype, and number of non-null objects of each column.

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
df=pd.DataFrame(animal_data)

print(df.describe())
print(df.info())
#directly found all with two actions
#to find all separately, following codes are used
count=df.count()
print('The count is:')
print(count)
mean=df.mean()
print('The mean is:')
print(mean)
std=df.std()
print('The standard deviation is:')
print(std)
datatype=df.dtypes
print('The datatype is:')
print(datatype)
#end of program

             age  weight(in kg)  height(in m)        BMI
count  20.000000      20.000000     20.000000  20.000000
mean    6.600000       9.050000      0.985000  10.586173
std     2.962929       2.981963      0.213431   5.250493
min     1.000000       5.000000      0.700000   3.472222
25%     4.500000       6.750000      0.800000   6.129630
50%     7.500000       9.000000      1.000000  10.101010
75%     9.000000      11.250000      1.200000  14.071429
max    10.000000      14.000000      1.300000  20.408163
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   animal         20 non-null     object 
 1   age            20 non-null     int64  
 2   weight(in kg)  20 non-null     int64  
 3   height(in m)   20 non-null     float64
 4   BMI            20 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 928.0+ bytes
None
The c

<ipython-input-47-491d45d9be33>:14: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean=df.mean()
<ipython-input-47-491d45d9be33>:17: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  std=df.std()


3)In the column "animal" find the number of unique values and the count of each of the unique values.

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
df=pd.DataFrame(animal_data)
unique_name=df['animal'].value_counts()
print('Number of unique values in "animal" column":', len(unique_name))
print('\nCount of each unique value in "animal column":')
print(unique_name)
#end of program

Number of unique values in "animal" column": 2

Count of each unique value in "animal column":
cat    13
dog     7
Name: animal, dtype: int64


4)Scale the data of columns "weight" and "height" in such a way that all the values lie between 0 and 1.

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
df=pd.DataFrame(animal_data)
#question requires us to use minimum and maximum scaling of height and weight columns
df['scaled_weight']=(df['weight(in kg)']-df['weight(in kg)'].min())/(df['weight(in kg)'].max()-df['weight(in kg)'].min())
df['scaled_height']=(df['height(in m)']-df['height(in m)'].min())/(df['height(in m)'].max()-df['height(in m)'].min())
print(df[['weight(in kg)', 'scaled_weight','height(in m)','scaled_height']])
#end of program

    weight(in kg)  scaled_weight  height(in m)  scaled_height
0              14       1.000000           1.3       1.000000
1              11       0.666667           1.2       0.833333
2               5       0.000000           1.2       0.833333
3               9       0.444444           0.9       0.333333
4               5       0.000000           1.2       0.833333
5              11       0.666667           1.1       0.666667
6              14       1.000000           1.0       0.500000
7               9       0.444444           1.0       0.500000
8              12       0.777778           0.8       0.166667
9               9       0.444444           0.7       0.000000
10              8       0.333333           0.8       0.166667
11             10       0.555556           0.7       0.000000
12             13       0.888889           0.9       0.333333
13             12       0.777778           1.0       0.500000
14              7       0.222222           0.7       0.000000
15      

5)Calculate the mean "height", "weight" and "age" of each different animal.
Hint: groupby()

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
df=pd.DataFrame(animal_data)
animals_mean=df.groupby('animal').mean()
print(animals_mean[['age','weight(in kg)', 'height(in m)']])
#end of program

             age  weight(in kg)  height(in m)
animal                                       
cat     6.769231       8.923077      0.938462
dog     6.285714       9.285714      1.071429


#### Read the data from the csv named "creditcard.csv". And perform the following tasks.

6)Find the number of males in the age range of 30 to 60 (including both 30 and 60 here), who have the occupation of "Self_Employed"

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
df=pd.read_csv('creditcard.csv')
#above code to see the data once
required_data=df[(df['Age']>=30)&(df['Age']<=60)&(df['Occupation']=='Self_Employed')&(df['Gender']=='Male')]
no_of_males=len(required_data)
print('The number of males in the age range of 30 to 60, who have the occupation of "Self_Employed", is:')
print(no_of_males)
#end of program

The number of males in the age range of 30 to 60, who have the occupation of "Self_Employed", is:
56231


7)Find the number of males and females who were active in the last 3 months (if the Is_Active column shows "Yes", that means that customer was active in the last 3 months, else he/she wasn't).

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
#for active customers
active_customer=df[df['Is_Active']=='Yes']
#separate by gender
gender_cc=active_customer['Gender'].value_counts()
print('Number of active males:')
print(gender_cc.get('Male',0))
print('Number of active females:')
print(gender_cc.get('Female',0))
#end of program

Number of active males:
55948
Number of active females:
39487


8)Find the percentage of null values in the column "Credit_Product", and replace them all with the value which is lesser among "yes" or "no" in the column.

In [ ]:
# SID 2023
# Author: Harsita Mohanty
#start of program
import pandas as pd
null_percent=(df['Credit_Product'].isnull().sum()/len(df)) * 100
rep_value=min(['yes','no',])
df['Credit_Product'].fillna(rep_value,inplace=True)
print('Percentage of null values in "Credit_Product" is:')
print(null_percent)
#end of program

Percentage of null values in "Credit_Product" is:
11.9340726421813


# <center>CONGRATULATIONS!! YOU FINALLY COMPLETED THE TASK-1.WE WILL BE COMING WITH EVEN MORE INTERESTING CONCEPTS IN THE NEXT TASK.
#    <center>TILL THEN **HAPPY MACHINE LEARNING!!.**</center>